.TH "C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/include/config.h" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/include/config.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'freertos/FreeRTOS\&.h'\fP
.br
\fC#include 'freertos/task\&.h'\fP
.br
\fC#include 'freertos/queue\&.h'\fP
.br
\fC#include 'freertos/timers\&.h'\fP
.br
\fC#include 'driver/gpio\&.h'\fP
.br
\fC#include 'driver/spi_master\&.h'\fP
.br
\fC#include 'driver/uart\&.h'\fP
.br
\fC#include 'driver/adc\&.h'\fP
.br
\fC#include 'driver/i2s\&.h'\fP
.br
\fC#include 'esp_adc_cal\&.h'\fP
.br
\fC#include 'esp_log\&.h'\fP
.br
\fC#include 'fft\&.h'\fP
.br
\fC#include 'i2s_sampler\&.h'\fP
.br
\fC#include 'mcp3201\&.h'\fP
.br
\fC#include 'midi\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_MOSI\fP   (GPIO_NUM_23)"
.br
.ti -1c
.RI "#define \fBSPI_MISO\fP   (GPIO_NUM_19)"
.br
.ti -1c
.RI "#define \fBSPI_SCLK\fP   (GPIO_NUM_18)"
.br
.ti -1c
.RI "#define \fBSPI_CS\fP   (GPIO_NUM_5)"
.br
.ti -1c
.RI "#define \fBSPI_DEV\fP   (VSPI_HOST)"
.br
.ti -1c
.RI "#define \fBMIDI_UART\fP   (UART_NUM_1)"
.br
.ti -1c
.RI "#define \fBMIDI_BAUD\fP   (115200)"
.br
.ti -1c
.RI "#define \fBMIDI_TX\fP   (GPIO_NUM_26)"
.br
.ti -1c
.RI "#define \fBMIDI_RX\fP   (GPIO_NUM_27)"
.br
.ti -1c
.RI "#define \fBDMA_CHAN\fP   1"
.br
.ti -1c
.RI "#define \fBADC_RES_BITS\fP   12"
.br
.ti -1c
.RI "#define \fBADC_RES\fP   (1 << ADC_RES_BITS)"
.br
.ti -1c
.RI "#define \fBINTERNAL_ADC_UNIT\fP   (ADC_UNIT_1)"
.br
.ti -1c
.RI "#define \fBINTERNAL_ADC_CHANNEL\fP   (ADC_CHANNEL_0)"
.br
.ti -1c
.RI "#define \fBINTERNAL_ADC_IO\fP   (GPIO_NUM_4)"
.br
.ti -1c
.RI "#define \fBAUDIO_BUFFER_SIZE\fP   512"
.br
.ti -1c
.RI "#define \fBF_SAMPLE_HZ\fP   44100"
.br
.ti -1c
.RI "#define \fBFFT_WINDOW_SIZE\fP   2"
.br
.ti -1c
.RI "#define \fBFFT_SIZE\fP   4096"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
@s-grundner 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-12-24
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
