.TH "fft_config_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fft_config_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "float * \fBinput\fP"
.br
.ti -1c
.RI "float * \fBoutput\fP"
.br
.ti -1c
.RI "float * \fBtwiddle_factors\fP"
.br
.ti -1c
.RI "fft_type_t \fBtype\fP"
.br
.ti -1c
.RI "fft_direction_t \fBdirection\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
