.TH "gitcon_context_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gitcon_context_t \- Gitcon Configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gitcon\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBi2s_sampler_t\fP * \fBsampler\fP"
.br
.ti -1c
.RI "\fBmidi_handle_t\fP \fBmidi_handle\fP"
.br
.ti -1c
.RI "QueueHandle_t \fBmidi_queue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gitcon Configuration\&. 


.PP
\fBParameters\fP
.RS 4
\fImcp3201\fP MCP3201 ADC 
.br
\fImidi_handle\fP MIDI Context Handler 
.br
\fImidi_queue\fP MIDI Queue 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
