.TH "C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/src/gitcon.h" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/src/gitcon.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgitcon_context_t\fP"
.br
.RI "Gitcon Configuration\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGITCON_LOG_LEVEL\fP   ESP_LOG_ERROR"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBgitcon_context_t\fP * \fBgitcon_handle_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBgitcon_init\fP (\fBgitcon_handle_t\fP *out_handle)"
.br
.RI "initializes gitcon device "
.ti -1c
.RI "esp_err_t \fBgitcon_exit\fP (\fBgitcon_handle_t\fP handle)"
.br
.RI "frees all resources "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
@s-grundner @Laurenz03 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-12-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "esp_err_t gitcon_exit (\fBgitcon_handle_t\fP handle)"

.PP
frees all resources 
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP gitcon context handler 
.RE
.PP
\fBReturns\fP
.RS 4
ESP_OK on success 
.RE
.PP

.SS "esp_err_t gitcon_init (\fBgitcon_handle_t\fP * out_handle)"

.PP
initializes gitcon device 
.PP
\fBParameters\fP
.RS 4
\fIout_handle\fP gitcon context handler 
.RE
.PP
\fBReturns\fP
.RS 4
esp_err_t ESP_OK on success, ESP_ERR_NO_MEM on memory allocation error 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
