.TH "mcp3201_config_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcp3201_config_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "spi_host_device_t \fBhost\fP"
.br
.ti -1c
.RI "gpio_num_t \fBcs_io\fP"
.br
.ti -1c
.RI "gpio_num_t \fBmiso_io\fP"
.br
.ti -1c
.RI "gpio_num_t \fBmosi_io\fP"
.br
.ti -1c
.RI "int \fBdma_chan\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
