.TH "mcp3201_context_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcp3201_context_t \- MCP3201 Context struct for internal use\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmcp3201_config_t\fP \fBcfg\fP"
.br
.ti -1c
.RI "spi_device_handle_t \fBspi\fP"
.br
.ti -1c
.RI "spi_transaction_t * \fBongoing_transaction\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MCP3201 Context struct for internal use\&. 


.PP
\fBParameters\fP
.RS 4
\fIcfg\fP MCP3201 Configuration 
.br
\fIspi\fP SPI Device Handle 
.br
\fIongoing_transaction\fP Ongoing SPI Transaction 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
