.TH "mcp3201_sampler_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcp3201_sampler_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmcp3201_handle_t\fP \fBmcp_handle\fP"
.br
.ti -1c
.RI "QueueHandle_t \fBdma_queue\fP"
.br
.ti -1c
.RI "QueueHandle_t \fBdsp_queue\fP"
.br
.ti -1c
.RI "size_t * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_pos\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
