.TH "C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/lib/midi/midi.c" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Smon/source/MTAP-MIDI-Guitar-Converter/firmware/MIDI-Testing/lib/midi/midi.c \- MIDI driver for ESP32\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'midi\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmidi_context_t\fP"
.br
.RI "MIDI Context (internal! not to be accessed externally, use midi_handle_t instead) "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMIDI_BYTE_SIZE_DEFAULT\fP   3"
.br
.ti -1c
.RI "#define \fBMIDI_BYTE_SIZE_SHORT\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBmidi_context_t\fP \fBmidi_context_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBmidi_init\fP (\fBmidi_context_t\fP **out_ctx, \fBmidi_config_t\fP *out_cfg)"
.br
.ti -1c
.RI "esp_err_t \fBmidi_exit\fP (\fBmidi_handle_t\fP midi_handle)"
.br
.RI "Exits MIDI and frees all resources\&. "
.ti -1c
.RI "esp_err_t \fBmidi_write\fP (\fBmidi_handle_t\fP handle, \fBmidi_message_t\fP *msg)"
.br
.RI "Writes MIDI Message to UART\&. "
.ti -1c
.RI "esp_err_t \fBmidi_read\fP (\fBmidi_handle_t\fP midi_handle, \fBmidi_message_t\fP *msg, TickType_t timeout)"
.br
.RI "Reads MIDI Message from UART\&. "
.in -1c
.SH "Detailed Description"
.PP 
MIDI driver for ESP32\&. 


.PP
\fBAuthor\fP
.RS 4
@s-grundner 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2022-12-23
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "esp_err_t midi_exit (\fBmidi_handle_t\fP midi_handle)"

.PP
Exits MIDI and frees all resources\&. 
.PP
\fBParameters\fP
.RS 4
\fImidi_handle\fP MIDI Handle to be freed 
.RE
.PP
\fBReturns\fP
.RS 4
esp_err_t 
.RE
.PP

.SS "esp_err_t midi_read (\fBmidi_handle_t\fP midi_handle, \fBmidi_message_t\fP * msg, TickType_t timeout)"

.PP
Reads MIDI Message from UART\&. 
.PP
\fBParameters\fP
.RS 4
\fImidi_handle\fP MIDI Handle to pass parameters 
.br
\fImsg\fP MIDI Message to be read 
.RE
.PP
\fBReturns\fP
.RS 4
esp_err_t 
.RE
.PP

.SS "esp_err_t midi_write (\fBmidi_handle_t\fP midi_handle, \fBmidi_message_t\fP * msg)"

.PP
Writes MIDI Message to UART\&. 
.PP
\fBParameters\fP
.RS 4
\fImidi_handle\fP MIDI Handle to pass parameters 
.br
\fImsg\fP MIDI Message to be sent 
.RE
.PP
\fBReturns\fP
.RS 4
esp_err_t 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
