.TH "midi_context_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
midi_context_t \- MIDI Context (internal! not to be accessed externally, use midi_handle_t instead)  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmidi_config_t\fP \fBcfg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MIDI Context (internal! not to be accessed externally, use midi_handle_t instead) 


.PP
\fBParameters\fP
.RS 4
\fIcfg\fP MIDI Config 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
