.TH "midi_message_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
midi_message_t \- MIDI Message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <midi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBparam1\fP"
.br
.ti -1c
.RI "\fBmidi_status_t\fP \fBstatus\fP"
.br
.ti -1c
.RI "uint8_t \fBchannel\fP"
.br
.ti -1c
.RI "uint8_t \fBparam2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MIDI Message\&. 


.PP
\fBParameters\fP
.RS 4
\fIstatus\fP MIDI Status Byte 
.br
\fIchannel\fP MIDI Channel 
.br
\fIparam1\fP MIDI Parameter 1 
.br
\fIparam2\fP MIDI Parameter 2 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
