.TH "midi_config_t" 3 "Wed Mar 8 2023" "Gitcon" \" -*- nroff -*-
.ad l
.nh
.SH NAME
midi_config_t \- MIDI UART Configuration\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <midi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uart_port_t \fBuart_num\fP"
.br
.ti -1c
.RI "uint \fBbaudrate\fP"
.br
.ti -1c
.RI "gpio_num_t \fBrx_io\fP"
.br
.ti -1c
.RI "gpio_num_t \fBtx_io\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MIDI UART Configuration\&. 


.PP
\fBParameters\fP
.RS 4
\fIuart_num\fP UART Port 
.br
\fIbaudrate\fP UART Baudrate 
.br
\fIrx_io\fP UART RX Pin 
.br
\fItx_io\fP UART TX Pin 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gitcon from the source code\&.
