mcp3201.h
ADC_CLK
typedef struct mcp3201_context_t* mcp3201_handle_t
esp_err_t mcp3201_init(mcp3201_handle_t *out_handle, const mcp3201_config_t *cfg)
Initializes the MCP3201 ADC device.
out_handle MCP3201 Handler to store initialization data cfg MCP3201 Configuration
esp_err_t mcp3201_exit(mcp3201_handle_t mcp_handle)
Exits the MCP3201 ADC device and frees all resources.
mcp_handle MCP3201 Device to exit ESP_OK on success
Referenced by gitcon_exit.
esp_err_t mcp3201_read(mcp3201_handle_t handle, uint16_t *out_value)
Reads a single value from the MCP3201 ADC.
handle MCP3201 Device out_value Value ESP_OK on success
mcp3201_sampler_t * mcp3201_sampler_start(mcp3201_handle_t mcp_handle, QueueHandle_t recv_queue, const size_t buffer_size, const size_t f_sample)
Starts the MCP3201 Sampler, which samples continuously and puts the samples into a queue.
mcp_handle MCP3201 Device Handler recv_queue queue to send the samples into buffer_size size of the audio buffer f_sample Sample rate mcp3201_sampler_t* Sampler Handler
References mcp3201_sampler_start.
Referenced by mcp3201_sampler_start.
void mcp3201_sampler_stop(mcp3201_sampler_t *sampler)
Stops the MCP3201 Sampler.
sampler Sampler Handler
References mcp3201_sampler_stop.
Referenced by gitcon_exit, mcp3201_sampler_stop.