mcp3201_sampler.c
RESAMPLE_DIVIDER
READER_TIMEOUT_MS
READER_TIMEOUT_TICKS
typedef struct mcp3201_context_t mcp3201_context_t
const char* TAG
TaskHandle_t sampler_task_handle
TaskHandle_t reader_task_handle
static void IRAM_ATTR sampler_task(void *arg)
static void IRAM_ATTR reader_task(void *arg)
mcp3201_sampler_t * mcp3201_sampler_start(mcp3201_handle_t mcp_handle, QueueHandle_t recv_queue, const size_t buffer_size, const size_t f_sample)
Starts the MCP3201 Sampler, which samples continuously and puts the samples into a queue.
mcp_handle MCP3201 Device Handler recv_queue queue to send the samples into buffer_size size of the audio buffer f_sample Sample rate mcp3201_sampler_t* Sampler Handler
References mcp3201_sampler_start.
Referenced by mcp3201_sampler_start.
void mcp3201_sampler_stop(mcp3201_sampler_t *sampler)
Stops the MCP3201 Sampler.
sampler Sampler Handler
References mcp3201_sampler_stop.
Referenced by gitcon_exit, mcp3201_sampler_stop.